### ISSUE TITLE
请问存在哪里?

### ISSUE THREAD

**Issue by daishuge** [mufeng510/Free-ChatGPT-API#2]
执行成功了,但是不知道被保存在哪里了
![image](https://github.com/mufeng510/Free-ChatGPT-API/assets/122254868/5b98f2fc-22de-4ad1-805e-c595ab8c5d65)

**Comment by mufeng510** [comment]
看起来你的脚本没有执行成功，看下你 `run_job.bat` 文件的内容

**Comment by daishuge** [comment]
![image](https://github.com/mufeng510/Free-ChatGPT-API/assets/122254868/6cae41b0-e72d-4cbc-8b57-ab7bd8a62ba8)
直接git clone下来的,请大佬看看

**Comment by daishuge** [comment]
这是一部分账号内容
![image](https://github.com/mufeng510/Free-ChatGPT-API/assets/122254868/a8dfb71c-9a96-41b4-9e7b-3416c4e3890a)

**Comment by mufeng510** [comment]
你使用conda了吗

**Comment by daishuge** [comment]
并没有诶，请问一定要嘛

**Comment by mufeng510** [comment]
没用的话需要删除`call conda activate pool`，然后保证python的环境安装好

**Comment by daishuge** [comment]
ok感谢，一会试一下

**Comment by daishuge** [comment]
感谢大佬,已经解决,谢谢你的项目!
