### ISSUE TITLE
pool token就是pk-xxxx不等于api key

### ISSUE THREAD

**Issue by jinde98** [mufeng510/Free-ChatGPT-API#3]
说明中提到的[ChatGPT-Next-Web]、[gpt_academic]项目中用到的是api key。access token和pool token之类的，无法在这两个项目中使用吧？pool token就是pk-xxxx不等于api key

**Comment by mufeng510** [comment]
`pool token` 可以当 api key 使用的，我目前就是这么使用的。我个人的理解是：pool token 可以认为是pandora提供的 key，通过这个key去访问了pandora的服务，类似openai官网提供的key访问openai的服务一样。而pandora的服务是模拟chatgpt服务。所以从用户体验上而言，使用pool token就相当于使用了openai的key一样。既然如此，为了大家理解方便，直接把pool token称之为 api key 应该是可以的，不需要过多理解原理，达到使用目的即可。

**Comment by jinde98** [comment]
在pandora的服务中，这个确实可以
