### ISSUE TITLE
pandora好像跑路了？仓库404 

### ISSUE THREAD

**Issue by lys623** [mufeng510/Free-ChatGPT-API#4]
大佬，pandora里实现使用pool_token调chatgpt的源码有开源吗？想自己部署一个，避免pandora宕机不可用，谢谢

**Comment by mufeng510** [comment]
库又被删了，难顶，fakeopen是不开源的
![image](https://github.com/mufeng510/Free-ChatGPT-API/assets/30998460/64ab1a78-ec3c-4778-bb8d-d6f83dadcc41)

**Comment by lys623** [comment]
![image](https://github.com/mufeng510/Free-ChatGPT-API/assets/4364314/1c1b4c11-a2f1-4eb8-b19c-4149fd9cc315)
接口突然出现这种错，真跑路了？

**Comment by lys623** [comment]
接口502了， @mufeng510 你可以用吗？

**Comment by mufeng510** [comment]
fakeopen服务已正常，可以正常获取token
