### ISSUE TITLE
Pandora现状？

### ISSUE THREAD

**Issue by Mzaxd** [mufeng510/Free-ChatGPT-API#6]
请问Pandora现在还能用吗 是不是凉凉了

**Comment by hth2500503914** [comment]
+1

**Comment by mufeng510** [comment]
在这里可以查看[fakeopen相关服务的状态](https://status.fakeopen.com/)，pandora目前可以正常使用的，脚本也能正常获取到pool token

**Comment by Mzaxd** [comment]
> 在这里可以查看[fakeopen相关服务的状态](https://status.fakeopen.com/)，pandora目前可以正常使用的，脚本也能正常获取到pool token

感谢！
