### ISSUE TITLE
获取不到 AccessToken，求救

### ISSUE THREAD

**Issue by lys623** [mufeng510/Free-ChatGPT-API#7]
最近登陆一直报错，service overload
![image](https://github.com/mufeng510/Free-ChatGPT-API/assets/4364314/53793dfe-0793-4235-8551-0227813a7f34)

**Comment by lys623** [comment]
看起来是登陆服务的问题，我挂美国节点，使用网页登陆是正常的

**Comment by mufeng510** [comment]
pandora-next/deploy#148

**Comment by mufeng510** [comment]
已修复

**Comment by Aurelius314** [comment]
请问{"detail":"service overload"}怎么解决？
