### ISSUE TITLE
能出个用python代码的教程吗？

### ISSUE THREAD

**Issue by long202258** [mufeng510/Free-ChatGPT-API#8]
能出个用python代码的教程吗？  每次自己运行下代码就行 这样比较简单

**Comment by mufeng510** [comment]
没明白，是python环境的安装吗

**Comment by long202258** [comment]
不是环境安装，是不要打包成 bat 格式 只弄成python代码就行&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mufeng510/Free-ChatGPT-API"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月1日(星期五) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mufeng510/Free-ChatGPT-API] 能出个用python代码的教程吗？ (Issue #8)





 
没明白，是python环境的安装吗

**Comment by mufeng510** [comment]
[auto_pool_token.py](https://github.com/mufeng510/Free-ChatGPT-API/blob/master/scripts/auto_pool_token.py)就是python代码，bat只是运行了这个py文件。

**Comment by long202258** [comment]
运行代码 保存的都是整个{"detail":"service overload"}




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mufeng510/Free-ChatGPT-API"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月1日(星期五) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mufeng510/Free-ChatGPT-API] 能出个用python代码的教程吗？ (Issue #8)





 
auto_pool_token.py就是python代码，bat只是运行了这个py文件。

**Comment by long202258** [comment]
大佬&nbsp;&nbsp;https://ai.fakeopen.com/v1/
这个还能用吗？ 有现在可以用的代码吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mufeng510/Free-ChatGPT-API"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月1日(星期五) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mufeng510/Free-ChatGPT-API] 能出个用python代码的教程吗？ (Issue #8)





 
auto_pool_token.py就是python代码，bat只是运行了这个py文件。

**Comment by mufeng510** [comment]
fakeopen现在停用了，需要自己部署PandoraNext

**Comment by jinde98** [comment]
> fakeopen现在停用了，需要自己部署PandoraNext

fakeopen API停用了，自己的账户如何取得share token来共享给他人。我没有超过一年时间的github账户，无法部署PandoraNext，很郁闷

**Comment by mufeng510** [comment]
> > fakeopen现在停用了，需要自己部署PandoraNext
> 
> fakeopen API停用了，自己的账户如何取得share token来共享给他人。我没有超过一年时间的github账户，无法部署PandoraNext，很郁闷

只能用自己的GitHub搭，没有就在某宝上买一个吧，这周我找时间用PandoraNext搭一下，看看能不能做个简单的脚本方便用

**Comment by mufeng510** [comment]
已修复
