### ISSUE TITLE
invalid parameters

### ISSUE THREAD

**Issue by lys623** [mufeng510/Free-ChatGPT-API#9]
![image](https://github.com/mufeng510/Free-ChatGPT-API/assets/4364314/acafd204-c0c9-4bbd-823d-03339d3316da)

**Comment by lys623** [comment]
pool token: 格式不正确，将重新生成。

这个也没生成

**Comment by mufeng510** [comment]
看着share token获取有问题，在win环境下能正常用吗

**Comment by lys623** [comment]
我是mac电脑，截图上显示login succes，说明api接口是通的，这个invalid parameters不知道是啥意思

**Comment by mufeng510** [comment]
login succes是acccess token获取成功了，invalid parameters是在获取share token时报错的，写脚本的时候没有考虑到mac，我这里没有mac的设备不好排查，我建了个Q群698974728，咱们在这说

**Comment by lys623** [comment]
突然可以了，先关掉了
